export default {
    questions: [],
    currentIndex: 0,
    currentTitle: "Select a question",
    currentOptions: [],
    userAnswers: {},
    confirmedAnswers: {},
    totalSeconds: 0,
    timeUp: false,
    timeLeft: '',
    timer: null,
    progress: 0,
    showPopup: false,
    showHelp: false,
    showContact: false,
    showCalculator: false,
    calcInput: "",
    showForm: false,
    selectedTestFilter: "",
    calcButtons: [
        "7",
        "8",
        "9",
        "/",
        "4",
        "5",
        "6",
        "*",
        "1",
        "2",
        "3",
        "-",
        "0",
        "C",
        "+",
        "=",
    ],
    strikethroughAnswers: {},
    isSubmittingAnswer: {}, // questionId => true/false
    showEndTestModal: false,
    isDarkMode: false,
    answerSent: false,
    resultLoaded: false,
    finalResult: {},
    showFilterPopup: false,
    
    filter: {
        selected: "", // values: 'answered', 'unanswered', 'flagged'
    },
    testId: null,

    
};
